# This is the default config for all environments. Check out custom-environment-variables.yml for all possible settings.

algolia:
  appId: 7AWZHGNJE2
  apiKey: f799a6e9a302535bd92bbfab65fb6311 # This is a search only API key. It's safe to check in.
  indexName: docs_site_dev
  libraryIndexName: dev_docs_sourcer-library-reference

googleAnalytics:
  trackingID: GTM-5TTJJGTL
